# YAML with API keys (secrets)
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-keys-config
  namespace: default
  labels:
    app: example
    version: "1.0"
data:
  slack_token: "xoxb-FAKE-SLACK-TOKEN-FOR-TESTING-ONLY"
  twilio_sid: "ACFAKE-TWILIO-SID-FOR-TESTING-ONLY"
  twilio_auth_token: "FAKE-TWILIO-AUTH-TOKEN-FOR-TESTING-ONLY"
  jwt_secret: "FAKE-JWT-SECRET-FOR-TESTING-ONLY"
  database:
    host: localhost
    port: 5432
    credentials:
      username: admin
      password: secret
  redis:
    host: localhost
    port: 6379
    password: redis-secret
  features:
    - authentication
    - authorization
    - logging
    - monitoring
