# Good YAML - Perfect indentation
apiVersion: v1
kind: ConfigMap
metadata:
  name: good-config
  namespace: default
  labels:
    app: example
    version: "1.0"
  annotations:
    description: "This is a well-formatted YAML file"
data:
  database:
    host: localhost
    port: 5432
    credentials:
      username: admin
      password: secret
  redis:
    host: localhost
    port: 6379
    password: redis-secret
  features:
    - authentication
    - authorization
    - logging
    - monitoring
  settings:
    debug: true
    verbose: false
    timeout: 30
